### ISSUE TITLE
taxonomy name does not change

### ISSUE THREAD

**Issue by Hansanghyeon** [WebDevStudios/custom-post-type-ui#846]
WordPress 
```log
[2022-03-21 08:23:22] production.ERROR: Undefined array key "sort" {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined array key \"sort\" at /var/www/html/wp-content/plugins/custom-post-type-ui/inc/taxonomies.php:1158)
[stacktrace]
#0 /var/www/html/wp-content/plugins/custom-post-type-ui/inc/taxonomies.php(1158): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/var/www/html/w...', 1158)
#1 /var/www/html/wp-includes/class-wp-hook.php(307): cptui_manage_taxonomies('')
#2 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /var/www/html/wp-admin/admin.php(259): do_action('cpt-ui_page_cpt...')
#5 {main}
"} 
```

<details><summary>WordPress info</summary>

```
### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: Asia/Seoul
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: undefined
environment_type: local
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 1,009.87 MB (1058923538 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 334.66 MB (350920800 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 227.32 MB (238363556 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 67.16 MB (70425224 bytes)
database_size: 33.52 MB (35143680 bytes)
total_size: 1.63 GB (1753776798 bytes)

### wp-active-theme ###

name: Sage Starter Theme (sage)
version: 10.0.0-dev
author: Roots
author_website: https://roots.io/
parent_theme: none
theme_features: sage, widgets-block-editor, soil, menus, editor-color-palette, editor-gradient-presets, editor-font-sizes, custom-units, custom-line-height, custom-spacing, disable-custom-colors, disable-custom-gradients, disable-custom-font-sizes, title-tag, post-thumbnails, align-wide, responsive-embeds, html5, customize-selective-refresh-widgets, widgets
theme_path: /var/www/html/wp-content/themes/sage
auto_update: Disabled

### wp-mu-plugins (2) ###

MU plugins subdirectory loader: author: (undefined), version: 0.1
WP Migrate DB Pro Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (24) ###

Advanced Custom Fields PRO: version: 5.11.4, author: Delicious Brains (latest version: 5.12), Auto-updates enabled
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.6.0, author: Automattic, Auto-updates enabled
All-in-One WP Migration: version: 7.56, author: ServMask, Auto-updates enabled
All-in-One WP Migration FTP Extension: version: 2.70, author: ServMask, Auto-updates enabled
All-in-One WP Migration Google Drive Extension: version: 2.71, author: ServMask, Auto-updates disabled
All-in-One WP Migration Unlimited Extension: version: 2.44, author: ServMask, Auto-updates enabled
Category Order and Taxonomy Terms Order: version: 1.6, author: Nsp-Code, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates enabled
Code Snippets: version: 2.14.3, author: Code Snippets Pro, Auto-updates enabled
Feed Post Thumbnail: version: 2.1.2, author: required, Auto-updates enabled
MainWP Child: version: 4.1.10, author: MainWP, Auto-updates enabled
Post Type Switcher: version: 3.2.1, author: Triple J Software, Inc., Auto-updates enabled
Post Views Counter: version: 1.3.11, author: Digital Factory, Auto-updates enabled
Preserve MainWP Connection: version: 1.0, author: Jay Holtslander, Auto-updates enabled
Redis Object Cache: version: 2.0.23, author: Till Krüss, Auto-updates enabled
Relevanssi: version: 4.15.1, author: Mikko Saari, Auto-updates enabled
Sassy Social Share Premium: version: 1.1.36, author: Team Heateor, Auto-updates disabled
SmartCrawl: version: 2.18.0, author: WPMU DEV, Auto-updates enabled
SVG Support: version: 2.4.2, author: Benbodhi, Auto-updates enabled
Symple Shortcodes: version: 2.1.3, author: AJ Clarke, Auto-updates disabled
WP Mail SMTP: version: 3.3.0, author: WPForms, Auto-updates enabled
WP Migrate DB Pro: version: 2.2.2, author: Delicious Brains, Auto-updates enabled
WP Migrate DB Pro Media Files: version: 2.1.0, author: Delicious Brains, Auto-updates enabled
WP Migrate DB Pro Theme & Plugin Files: version: 1.2.0, author: Delicious Brains, Auto-updates enabled

### wp-plugins-inactive (3) ###

Custom Post Type UI: version: 1.11.1, author: WebDevStudios, Auto-updates enabled
Hustle: version: 7.4.13.1, author: WPMU DEV, Auto-updates disabled
Taxonomy Switcher: version: 1.0.4, author: WebDevStudios, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.5.0
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.11.0-38-generic x86_64
httpd_software: Apache/2.4.51 (Debian)
php_version: 8.0.13 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.74.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.6.5-MariaDB-1:10.6.5+maria~focal
client_version: mysqlnd 8.0.13
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wp_mail_smtp ###

version: 3.3.0
license_key_type: lite
debug: No debug notices found.
lite_install_date: Nov 30, 2021 @ 5:04pm
```

</details>

**Comment by tw2113** [comment]
Clicking to edit the taxonomies you have and just clicking the save button should clear those up for a quick win, however I should also do some better diligence around empty checks as well.

@ Me, follow along with what we have for `show_in_quick_edit`

**Comment by tw2113** [comment]
Handled in 62b181b
